### ISSUE TITLE
Transform the cut segments/models to the mandibular curve to reconstruct the defect

### ISSUE THREAD

**Issue by cmfsx** [lassoan/SlicerBoneReconstructionPlanner#10]

**Comment by mauigna06** [comment]
This is one of the things done in the last commit. I achieved the following picture:
![ppff1](https://user-images.githubusercontent.com/19158307/103135797-baa13600-4699-11eb-9aa9-0b7a4d92cb50.png)

One things is problematic: there are some small overlaps between the bones. For example look here (it's resected mandible and fibula bone piece 0 intersection on axial view):
![overlap](https://user-images.githubusercontent.com/19158307/103135844-1f5c9080-469a-11eb-805a-c86c119ce329.PNG)

I found the following:
- a overlap of 1.2mm for intersection between resected mandible and fibula bone piece 0
- a overlap of 0.25mm for intersection between fibula bone piece 0 and fibula bone piece 1
- a overlap of 0.25mm for intersection between fibula bone piece 1 and resected mandible

**Comment by cmfsx** [comment]
I think this is correct. This is the objective of the project. This is the part that is going to be removed surgically from the fibula. The objective is to create this plane for the surgical saw.  

![103135844-1f5c9080-469a-11eb-805a-c86c119ce329](https://user-images.githubusercontent.com/57766971/103136110-cbfc3980-46bd-11eb-97d3-7457295dc1b5.png)

Usually, this space should be (thickness of the saw)  0.5 mm to 1.25 mm. 

![sawhandpieces-bigteaser](https://user-images.githubusercontent.com/57766971/103136126-f77f2400-46bd-11eb-8e08-64ad838d1d82.png)

The ideal scenario is that the surgeon only specifies the space for the saw (0.5 to 1.25 mm) and the Slicer calculate the position and the thickness setting will vary with the kind of saw system and the surgeon's preference. On principle less space more accurate the cut but difficulty in instrumentation and more space less accurate but easy to cut.

**Comment by mauigna06** [comment]
> On principle less space more accurate the cut but difficulty in instrumentation and more space less accurate but easy to cut.

I don't know if more space would mean less accurate because you can set up the cutting planes to compensate that and the personalized surgical guide would cut the bone pieces with the exact size needed

**Comment by cmfsx** [comment]
> I don't know if more space would mean less accurate because you can set up the cutting planes to compensate that and the personalized surgical guide would cut the bone pieces with the exact size needed

I was referring to this space. 
![1](https://user-images.githubusercontent.com/57766971/103227585-002a6100-492f-11eb-8a10-468ff2095906.png)

I tried the new updates and it works nicely.  Just to give you an idea of how I work with it and if your workflow is different from mine.  

https://youtu.be/5kFuLer_aqw

https://youtu.be/s7G5_N3ydTw

I have shared this with a few of my friends who are working with the flap so they can use it and give us some feedback. I will wait a bit more time before we do the 3D printing to iron out the intersection. 

Also will it be possible to capture the rotation of the plane around the long axis in term of transforming back to the mandible? 

![Screenshot from 2020-12-28 17-25-56](https://user-images.githubusercontent.com/57766971/103229644-c3149d80-4933-11eb-9c90-822c466d5a25.png)

**Comment by lassoan** [comment]
More space is less accurate because it means that you have larger gap between the segments. You need to plan to have some gap because then you have some freedom of movement to compensate for inaccuracies in printing, cutting, small amount of debris and blood getting on the pieces, etc. However, you want to keep the bone segments close to each other for mechanical stability and it probably also improves bone health.

> Also will it be possible to capture the rotation of the plane around the long axis in term of transforming back to the mandible?

This is crucial and will be automatically fulfilled if cutting planes are computed by defining coordinate systems and computing transforms between them. Ad hoc concatenation of a series of translations and rotations is hard to get right. We'll discuss this with Mauro today.

**Comment by mauigna06** [comment]
> Just to give you an idea of how I work with it and if your workflow is different from mine.

I liked your workflow. A suggestion: I would always set between space to some value (around 15mm) so the bone pieces don't touch; a note: the first cutting fibula plane is located near the first point of the fibula line so if you start drawing the fibulaLine from the distal side of the fibula the first fibula plane would be located distally also

I'll update the code so the bone pieces have different colors.
Also I'll update the documentation and the code so is more clear how the module works.

**Comment by cmfsx** [comment]
> I'll update the documentation

I can help you with that

**Comment by cmfsx** [comment]
Today I received feedback from Prof Manjula Attygalla, a person who has easily performed the highest number of fibula flaps in Sri Lanka. He was very impressed with what we have done to start with. 

He suggested making it possible to import the intraoral scan of the occlusion and rather than concentrating on the mandibular form, do the planning at the occlusal level. (where upper and lower teeth meet). His suggestion made me think and I have several ideas that will make this have features that none of the commercial software has and also suggest a paradigm shift in planning and solve the biggest problem in this kind of surgery - The condyle. 

Maybe this is too much information and I may be confusing you all but just to have a general idea of what I am thinking. 

Planning at an occlusal level is something that Commercial software does not allow to the best of my knowledge. 

![image](https://user-images.githubusercontent.com/57766971/103422198-7eda0500-4ba0-11eb-99e3-0deb57ea7910.png)

So Import the Scan + register it (Functionality already there in Slicer, nothing to be done except maybe make it more accessible within our GUI perhaps ?, the downside is that it will make our GUI to clutter ? ) 

Then what I thought was, 
We can make the workflow like in orthognathic surgical planning rather than cancer reconstruction. (This idea has not been proposed or published as of now),

To occlusal level curve, we can add dental implants,  (constrain it to curve) Also imagine the occlusal scans are superimposed on the segments now on the photo below. 

![Screenshot from 2020-12-31 19-21-49](https://user-images.githubusercontent.com/57766971/103422678-f3ae3e80-4ba2-11eb-96a1-cad1782b28ca.png)


Follow our workflow as usual but this time surgeon will have information about dental implant (oral recon plan) so he can decide on the cuts much better.  And he will be able to generate the surgical guide for the dental implants as well from this. 

![Screenshot from 2020-12-31 19-20-30](https://user-images.githubusercontent.com/57766971/103422773-59022f80-4ba3-11eb-8f27-614fd765e516.png)

And now this is what  I thought, 

We add the SlicerIGT+Plus toolkit with the 3D printed articulator (optical) to be used with the webcam (or any other).
Like here 
https://www.youtube.com/watch?v=MOqh6wgOOYs

Now we will be able to register the patient's jaw movements with this and this will enable the orthognathic kind of surgical planning in reconstruction.    

So if we manage to incorporate all this our planner will differ from any other commercial software by,  

1. Occlusal level planning of reconstruction 
2. Ability to plan oral rehabilitation at the same place
3. Ability to generate the dental implant cutting guide then and there. 
4. Ability to capture the condylar movement (optical tracking using cheap webcams) which will enable jaw movement information which in turn will solve the biggest problem of fibula flaps-- the condylar position.

**Comment by mauigna06** [comment]
> Today I received feedback from Prof Manjula Attygalla, a person who has easily performed the highest number of fibula flaps in Sri Lanka. He was very impressed with what we have done to start with.

This is great.

For everything else you wrote: I'm going to wait for what Andras has to say about it before I talk.

PD: The bone pieces transform formula was corrected and now bone segments don't intesect so it is confirmed that they are ready to be 3D printed. Now rotation along the long axis works: MandiblePlane0 rotation makes BonePiece0 rotate and so on

**Comment by cmfsx** [comment]
> The bone pieces transform formula was corrected and now bone segments don't intesect so it is confirmed that they are ready to be 3D printed

I tried your branch and it works well. What does the tick right fibula means?

**Comment by mauigna06** [comment]
> What does the tick right fibula means?

It means you tick the button if the fibula is the one from the right side (leave it unticked if the fibula is the left one). This is done to make the fibula X axis always point in the medial direction. I'll change the text of the button in a next commit because I think it is not clear enough what the button is meant for

@cmfsx, can you medically document why and for what you use our module when you make the 3D printed models so I can use that for my final project presentation? (if it isn't too much trouble)

**Comment by mauigna06** [comment]
@cmfsx The merge has been done
