### ISSUE TITLE
Automated cutting plane calculation based on mandibular curve

### ISSUE THREAD

**Issue by cmfsx** [lassoan/SlicerBoneReconstructionPlanner#12]

**Comment by mauigna06** [comment]
@lassoan can you give a broad sense introduction so I can start working on this? (e.g. creating a control point for the origin of the plane over a vtkMRMLMarkupsCurveNode, getting the tangent of the curve in that point, etc)

**Comment by lassoan** [comment]
Add on observer to the newly created plane node. If a point is added, get the closest point position on the curve, and use GetCurvePointToWorldTransformAtPointIndex to get the transform you need with a single call. A transform contains the plane position and all its axis directions in a 4x4 matrix.
