### ISSUE TITLE
Register sample data sets

### ISSUE THREAD

**Issue by lassoan** [lassoan/SlicerBoneReconstructionPlanner#14]
To make testing easier, add registration of sample data sets into SampleData module. This allows single-click loading of testing data (fibula and mandible images for now, later we can add segmentation and curves as well). There is already an example in the module for registering custom two same data sets, they just need to updated with the correct name, link, and git hash.

**Comment by mauigna06** [comment]
done

**Comment by lassoan** [comment]
Great! Please always refer to the issue number in commit comment.

Adding "Fixes #14" associates the commit with this issue and closes it automatically.

Adding "See #14" just associates the commit with this issue, so it is easy to find related code changes.
