### ISSUE TITLE
Requeriment of more info about the workflow to continue the devepment

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerBoneReconstructionPlanner#23]
@cmfsx Can you upload an scene made with the module that has a fibula bone model and the fibula planes positioned as you would put them to plan a surgery (I think you said something related with that the intersections of the planes should be on the lateral side). I want this file to see how the sawBoxes should be transformed to place

**Comment by mauigna06** [comment]
I also need the transforms that affect the fibulaPlanes. They are called "Mandible2Fibula TransformX_A" and "Mandible2Fibula TransformX_B". Maybe it's just most confortable to put everything you have in the scene in a Medical Record Bundle

**Comment by cmfsx** [comment]
I have created two test MBR files. In the first one, The fibula line is drawn from the superior side. In the second file seto2.mrb I have position the mandibular planes the way I want. It is the reconstruction that I expect to achieve in the mandible.  Is this all the info you need ? if there is anything else let me know please. 

https://mau.box.com/s/oxi5rttdqkjns2pc0mmmbbwvymckqil9

**Comment by cmfsx** [comment]
@mauigna06 I could not find the newly added functionality as of now. I  used the latest main branch but nothing new was there. I could not see an experimental branch also.

**Comment by mauigna06** [comment]
Hi Manjula. Here are two pictures to show you how to find it:
![collapsed](https://user-images.githubusercontent.com/19158307/107345389-42080480-6aa2-11eb-84c0-5e35562bca14.PNG)
![uncollopsed](https://user-images.githubusercontent.com/19158307/107345398-47654f00-6aa2-11eb-8099-04470d8617c6.PNG)

**Comment by cmfsx** [comment]
Thanks, @mauigna06  that's was very strange as i did not see the updated GUI in Slicer for some reason until I restarted.  Anyway now I can see it.

**Comment by cmfsx** [comment]
@mauigna06 

@mauigna06  Great!  yes it is working as intended. 

![Screenshot from 2021-02-09 10-58-28](https://user-images.githubusercontent.com/57766971/107347190-d9cb1a00-6ac5-11eb-9b3f-d851516acbf3.png)

**Comment by cmfsx** [comment]
@mauigna06 before the code gets more complicated can we change the cylinders to screw size/diameter and also slit to groove? 

Also please note that these sizes should be adjustable. I would prefer rather than a list of size to make it dynamic because that would make the program more versatile when it comes to 3D printing. The users can adjust according to their printer/s  settings which might not print exactly the size we want.  Because we want it to be accurate enough in cheap FDM printers as well.

**Comment by lassoan** [comment]
Note that size and location of the screw holes do not affect accuracy (they should be just large enough for the screw shaft to pass through comfortably but not the screw head).

An additional distance (typically 0.05-0.2mm) is indeed necessary to be added as a gap _everywhere_ where a 3D-printed surface (with all its inaccuracies) meets a physical surface. It is not just for screws but for the bone surface as well. We should try to use the same distance value everywhere (or have two values, one for clearance and another for transition fit - see [here](https://formlabs.com/blog/3D-printing-tolerances-for-engineering-fit/)) and only allow separate tuning of if we find that it is necessary (e.g., we want to have an additional clearance for the bone cutter).

**Comment by mauigna06** [comment]
> An additional distance (typically 0.05-0.2mm) is indeed necessary to be added as a gap everywhere where a 3D-printed surface (with all its inaccuracies) meets a physical surface. It is not just for screws but for the bone surface as well.
So how does this affect the code? I suppose we need clearance tolerance for screw holes diameter and saw groove (that can be coded, for example 0.2mm). And a transtion tolerance when creating the surgical guide base, to do this, two segments should be created, one with 6mm extrusion (hollow effect) and another with 0.1mm extrusion, and make a boolean difference between them (this isn't coded and should be done by who makes the surgical guide base)

**Comment by lassoan** [comment]
You add these clearances in the Slicer module. For example, you may apply margin effect to slightly enlarge the bone segment; or slightly shift cutting plane positions.

**Comment by mauigna06** [comment]
> You add these clearances in the Slicer module.

I can add one/two spinBox/es to set up the clearance and the transition fit.

> For example, you may apply margin effect to slightly enlarge the bone segment;

So you want a button to use margin effect in the module?

> or slightly shift cutting plane positions.

Why slightly shift cutting plane positions? Aren't them ideal? I think we should slightly increase groove and make the sawBoxes a little wider to achieve the clearance

**Comment by lassoan** [comment]
> Why slightly shift cutting plane positions? Aren't them ideal? I think we should slightly increase groove and make the sawBoxes a little wider to achieve the clearance

Yes, I meant the same thing. The user will enter the desired thickness of the slot but when we compute the cutting plane positions we will shift them slightly, depending on the accuracy of the 3D printer (probably both sides, by equal amount).

It is very important not to add tolerances whenever we feel that something is not quite right, but define very clearly which offset means what. The offset that we apply to planes to account for saw blade thickness is completely different from the offset that we add to compensate for 3D printing inaccuracy and material properties. This allows for example to implement the same surgical plan with different tools (e.g., a different hand saw, different 3D printer).

To make things a bit more clear, let's clean up the vocabulary that we use in the design document, discussions, and in the code:
- use "miter box" (especially for the one that is placed on the fibula) or "cutting guide" (as the mandible cutting guide does not resemble to a miter box very much) instead of "saw box"
- "slot" (thin rectangular holes in the miter box to guide the saw) - instead of "groove"

**Comment by mauigna06** [comment]
@cmfsx, @lassoan: In the last commit the module is ready to make an anatomical fibular surgical guide

**Comment by mauigna06** [comment]
First surgical guide made with the module, mirrors:
https://easyupload.io/quj9di
https://file.io/77KwEkSmTLnw

**Comment by lassoan** [comment]
This looks very promising!

The the slots should be longer (need to go beyond the bone by at least 5-10mm on both sides) and the wall of the slots should be constant height (taller than just the shall that is placed on the bone).

**Comment by cmfsx** [comment]
@mauigna06 great work. STL was good also there was no manifolds and very few problems. ready to print i guess.  But the design needs to be readdressed. the slots needs to go above the bone and allow enough space from top and bottom to insert the saw blade. 

Also don't need a very big base plate. (waste of plastics) 

For some reason i could not generate it. maybe this does not work in slicer stable ? 

![Screenshot from 2021-02-12 21-24-24](https://user-images.githubusercontent.com/57766971/107819235-1f633d80-6d79-11eb-9fdd-0684b75fa94e.png)

**Comment by mauigna06** [comment]
> The the slots should be longer (need to go beyond the bone by at least 5-10mm on both sides)

I'll add a spinBox to set it up.

> and the wall of the slots should be constant height (taller than just the shall that is placed on the bone).

Yes, we need to make a union of surgicalGuideBase with BiggerMiterBoxes so after the difference with the normalMiterBoxes there is a guided rectangular hole with a thick wall. This may need the user to go back and forth between the segmentEditorModule and our module which is uncomfortable but workable.

> But the design needs to be readdressed. the slots needs to go above the bone and allow enough space from top and bottom to insert the saw blade.

If I understood right you ask for something similar to the quote above.

> For some reason i could not generate it. maybe this does not work in slicer stable ?

You need latest preview release and to install the Slicer's Sandbox extension.

**Comment by cmfsx** [comment]
> If I understood right you ask for something similar to the quote above.

@mauigna06 can we make a quick call tomorrow or on sunday? it is difficult to explain with words,

I will give it a go I am not sure i will explain this correctly. 

There can be two instances, one surgeon might be using an oscillating saw and the other a reciprocating saw.  Especially in the case of reciprocating saw you need some purchase on the bone from the top or bottom. Also important part is the mitter boxes. they should be of sufficient thickness and strong enough and also may be thick enough to accidental cuts/slips (it will also depend on the material). the screw holes at the fibula level is only to keep the guide in place. When you cut it there is a significant amount of vibration, especially after one end is cut and also with small pieces.  The base should be of minimum size (to save the material waste)  and hold the mitter boxes together. 

If i don't make sense let's have a brief call.

**Comment by mauigna06** [comment]
Yes. We can have a call, are you okey with 2pm EST (16:00 from Buenos Aires)? Andras would you like to be present? Should we do it another day so you can come?
Here are some pictures I have of surgical guides made with propietary software or by research groups:
https://gofile.io/d/Wzx0bT

**Comment by lassoan** [comment]
I'm try to join but I am not sure yet if I can. You can just go on and meet anyway.

**Comment by cmfsx** [comment]
> We can have a call, are you okey with 2pm EST

Yes 8 pm EST is ok. But  if you can manage even later is better for me today.  



> Here are some pictures I have of surgical guides made with propietary software or by research groups:
Yes i can explain the different purposes of each as they have their advantages and their disadvantages.

the one that is generated right now can be used and do the job. But it can be easily refined to a much much better version and at the same time, we need to consider the material cost/waste and reduce it as well.

**Comment by mauigna06** [comment]
> the one that is generated right now can be used and do the job.

In fact, this surgeon appears to use a method similar to what we can achieve right now but in Blender: https://youtu.be/FBqY-HvMqrw?t=3949
For what I have talked with him he uses this method in his daily practice and teaches other surgeons to do the same

> But it can be easily refined to a much much better version

I think with some work making boolean operations with miterBoxes, improving the module's GUI, and using the segment editor we can have results like this:
![imagen](https://user-images.githubusercontent.com/19158307/107849347-7ac51800-6dd9-11eb-8194-482fd502f9c8.png)

Because of that reason I'd like to pospone the meeting till Andras can come so we can have also a coding aspect of the talk also. Andras please tell us when you'd be available.

> and at the same time, we need to consider the material cost/waste and reduce it as well.

The maximum material input is due to the surgicalGuideBase, if you keep it tight it uses less material but is harder to segment. So I don't know if we should spend efforts making it tighter because it only spends 2 or 3 more dollars on plastic for the 3Dprinter

**Comment by mauigna06** [comment]
The surgeon that commented on https://discourse.slicer.org/t/custom-fitting-surgical-guides-on-slicer/14270/. Gave me his contact info to invite him to a meeting. Maybe after next meeting we can invite him. Do you agree?

**Comment by lassoan** [comment]
Today 2pm EST works for me.

**Comment by mauigna06** [comment]
Then today 2pm EST we do the call through Skype

**Comment by cmfsx** [comment]
> Then today 2pm EST we do the call through Skype
Share the link

**Comment by mauigna06** [comment]
> Share the link

Sent

**Comment by mauigna06** [comment]
Not bad.
![Screenshot](https://user-images.githubusercontent.com/19158307/107986906-ce875b00-6fab-11eb-86c1-76cb60d2309d.png)

Here's the stl:
https://gofile.io/d/VGW1sz

I suggest you print it with the bone touching part facing upwards so it's smoother

**Comment by lassoan** [comment]
If we use the Segment editor for Boolean operations then we need to increase the internal labelmap resolution. This uneven edge might lead to difficulties in moving the saw blade (or small plastic particles removed from the side of the slot):

![image](https://user-images.githubusercontent.com/307929/107998416-152c8380-6fb3-11eb-9642-a9d3c56a493f.png)

Was vtkbool not stable enough for combining meshes?

**Comment by lassoan** [comment]
This part is not printable or may break off:

![image](https://user-images.githubusercontent.com/307929/107998545-663c7780-6fb3-11eb-925b-90b65777bfe0.png)

In such cases the slots should either be made a bit taller (to make the wedge thicker) or lower (to make the wedge disappear completely).

Another potential issue: this wedge may break off or bend during sawing:

![image](https://user-images.githubusercontent.com/307929/107999072-933d5a00-6fb4-11eb-8210-d60f268764b7.png)

It would be better to connect both ends of the wedge to the sides of the miter box.

**Comment by mauigna06** [comment]
Sorry for the buzz guys, I'll be more careful about what I upload

> If we use the Segment editor for Boolean operations then we need to increase the internal labelmap resolution.

I didn't know this. How do I do it? Do I need to resample the scalarVolume? 
I'll make a comment about the process of making the surgical guide later.

> Was vtkbool not stable enough for combining meshes?

```    
    for i in range(len(biggerSawBoxesModelsList)):
      combineModelsLogic.process(surgicalGuideModel, biggerSawBoxesModelsList[i], surgicalGuideModel, 'union')

    for i in range(len(cylindersModelsList)):
      combineModelsLogic.process(surgicalGuideModel, cylindersModelsList[i], surgicalGuideModel, 'difference')

    for i in range(len(sawBoxesModelsList)):
      combineModelsLogic.process(surgicalGuideModel, sawBoxesModelsList[i], surgicalGuideModel, 'difference')

    #combineModelsLogic.process(surgicalGuideModel, self.fibulaModelNode, surgicalGuideModel, 'difference')`
```
If this last line is not commented the result is an emptyModel. So this operation needs to be done inside the segment editor.

> If you come across vtkbool (combineModelsLogic) failure then creaet an issue here, add a link to the models, then I'll check if I can fix it by preprocessing and if not then we submit it as an issue to vtkbool.

I don't know if the process I'm using to create the surgical guides is optimal. Right now it is this: make a hollow effect of the fibulaSegment to get a cocoonSegment, convert it to a cocoonModel, make boolean union to cocoonModel with biggerMiterBoxes and make boolean difference with miterBoxes and cylinders (with combineModelsLogic). Convert the resulting model surgicalGuidePrototypeModel to a segment surgicalGuidePrototypeSegment. Do a boolean difference (on the segment editor) to the surgicalGuidePrototypeSegment with the fibulaSegment. Use the scissors to get the final surgicalGuideSegment (cutting the excess material). Convert it to a surgicalGuideModel

> We can use Segment editor for Boolean operations but then we need to reduce spacing of the internal labelmap representation to something like 0.1mm or less. This would mean that we need to work with a labelmap resolution of something like 3000x400x400, which is doable, but may slow things down and there is a risk that the user might run out of memory (especially if we want really smooth model and so we go below 0.1mm spacing, something like 0.05 or 0.025).

Okay, so we need to test if we can make a process of making the surgical guides that only needs the combineModels module and not the segmentEditor. I need your help brainstorming on this.

1. The firstSurgicalGuide (the one where slots have no height) is completely done with combineModels. That is: make a hollow effect of the fibulaSegment, cut with scissors to have a surgicalGuideBaseSegment, convert it to surgicalGuideBaseModel, make a boolean difference to the surgicalGuideBaseModel with the miterBoxes and cylinders. Observations: hollow effect is currently used with 6mm, it can be made with 8mm or 10mm. This would allow for more exact saw movement.
2. Another way to make them using only the combineModels module would be:  make a hollow effect of the fibulaSegment, cut with scissors to have a surgicalGuideBaseSegment, convert it to surgicalGuideBaseModel,  make a boolean difference to biggerMiterBoxes with the surgicalGuideBaseModel (biggerMiterBoxes should be narrower than surgicalGuideBaseModel so the cut leaves two islands inside each biggerMiterBox). Translate the biggerMitterBoxes 3mm in -miterBoxAxisY direction (normal to the fibulaModel and along slotHeight). Make boolean union of surgicalGuideBaseModel with biggerMiterBoxes, make boolean difference to the resulting model with cylinders and miterBoxes. Run vtkConnectivityFilter to the surgicalGuidePrototypeModel to get the surgicalGuideModel 
3. Another way to make them using only the combineModels module would be:  make a hollow effect of the fibulaSegment, cut with scissors to have a surgicalGuideBaseSegment, convert it to surgicalGuideBaseModel. Translate the biggerMiterBoxes so the only touch half of the surgicalGuideBaseModel. Then, make boolean union of surgicalGuideBaseModel with biggerMiterBoxes, make boolean difference to the resulting model with cylinders and miterBoxes.

Of all these methods I'd like to try method 3 next. Please advice if you have another method idea.

> This part is not printable or may break off:
In such cases the slots should either be made a bit taller (to make the wedge thicker) or lower (to make the wedge disappear completely).

I think this problem can be avoided incrementing the distance between fibulaPlanes. I can't understand what you propose: if slots are a bit taller (the wedge would be smaller not thicker) and viceversa

> Another potential issue: this wedge may break off or bend during sawing:
It would be better to connect both ends of the wedge to the sides of the miter box.

Yes. I'll try to do that with method 3.

**Comment by lassoan** [comment]
> > If we use the Segment editor for Boolean operations then we need to increase the internal labelmap resolution.
> 
> I didn't know this. How do I do it? Do I need to resample the scalarVolume?

See https://slicer.readthedocs.io/en/latest/user_guide/modules/segmenteditor.html#segmentation-is-not-accurate-enough. Simplest is to resample the fibula volume before segmentation.

> Okay, so we need to test if we can make a process of making the surgical guides that only needs the combineModels module and not the segmentEditor. I need your help brainstorming on this.

We can use normal (not super-high) resolution segmentation for creating shell, create plane cuts at non-critical locations. The only thing that we should probably do in the mesh domain are the sides of the slot, because that must be as smooth as possible (only the 3D printer's resolution should be the limit).

It is hard to interpret the description of the 3 options. If you want me to give feedback then you need to draw images or capture screenshots to explain them, but if you like option 3 then we can go with that and see if we run into any issues.

> I think this problem can be avoided incrementing the distance between fibulaPlanes. I can't understand what you propose: if slots are a bit taller (the wedge would be smaller not thicker) and viceversa

Slightly taller slot walls may make some wedges smaller but after some point, the slots diverge and there will be more space between them. Of course there is a limit due to blade length, so increasing wall height is not always a good solution. Probably we should just detect issues and let the user resolve it by choosing between adjusting angles, distances, or wall heights.

**Comment by mauigna06** [comment]
I'll be coding a lot less these following weeks because I have to study for my last exam. I having experimenting with transforms and boolean operations and I have got acceptable results (without using the segment editor). I'll write more about this in the future

**Comment by lassoan** [comment]
Sounds great!
Good luck with your exam.

**Comment by mauigna06** [comment]
I found the difference of "fibula" with "FibularSurgicalGuidePrototype" doesn't work (the result is an empty model). Hopefully I won't need to make this kind of operation the way I'm doing things right now with transforms and boolean operations (with the combineModels module) but I wanted to let you know that I found this problem.
[differenceDoesntWork.zip](https://github.com/lassoan/SlicerBoneReconstructionPlanner/files/6005606/differenceDoesntWork.zip)

**Comment by lassoan** [comment]
See this error: "Contact ends suddenly at point 630.".

The task is very hard because half of the faces in the two meshes are coincident. Probably moving one of the models by 0.01 mm would resolve the issue.

I'll submit this issue to vtkbool.
