### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by cmfsx** [lassoan/SlicerBoneReconstructionPlanner#24]
Are we going to keep the name "SlicerBoneREconstructionPlanner"  should we plan to change it narrowing the scope?  

I will ask someone to work on a logo so can we finalize a name? 

@lassoan are there any rules for the slicer extension logo?

**Comment by lassoan** [comment]
This extension will host modules for planning all kinds of bone graft procedures (sharing low-level infrastructure between all of them). When we will have highly specialized modules in this extension then we can start using more specific names for them. So far, the module is still very generic (the only application-specific part is the "fibula" and "mandible" words).
