### ISSUE TITLE
vtkClipPolyData not working right

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerBoneReconstructionPlanner#25]
I generate an intersectionModel with the fibulaModel and a fibulaPlane with vtkCutter. Then I generate semiIntersectionModel with intersectionModel and a plane that has a normal equal to fibulaZ (the direction of the fibulaLine) and an origin equal to fibulaPlaneOrigin.
When the normal of first plane and normal of the second plane differ by very little the result of the clipping (semiIntersectionModel) is empty and has no points. How to correct this?
[Here](https://gofile.io/d/EXgHJ3) is an scene showing the problem in "semiIntersection0_A" and "semiIntersection0_B"
It appears that vtkClipPolyData is not sensitive enough.

Here is the function to create semiIntersections:
```
def getIntersectionBetweenModelAnd1PlaneWithNormalAndOrigin(self,modelNode,normal,origin,intersectionModel):
  plane = vtk.vtkPlane()
  plane.SetOrigin(origin)
  plane.SetNormal(normal)

  clipper = vtk.vtkClipPolyData()
  clipper.SetInputData(modelNode.GetPolyData())
  clipper.SetClipFunction(plane)
  clipper.Update()

  intersectionModel.SetAndObservePolyData(clipper.GetOutput())

#call
semiIntersectionModel = slicer.mrmlScene.AddNewNodeByClass('vtkMRMLModelNode','semiIntersection'
semiIntersectionModel.CreateDefaultDisplayNodes()
getIntersectionBetweenModelAnd1PlaneWithNormalAndOrigin(intersectionModel,fibulaZ,fibulaPlaneOrigin,semiIntersectionModel)

**Comment by lassoan** [comment]
Why do you need to cut with the second plane? Can you draw a sketch that shows these operations?

**Comment by mauigna06** [comment]
> Why do you need to cut with the second plane?

I needed it to have the half of the intersectionModel so I can compute the averageNormal over the semiIntersectionModel.

Thanks for the help Andras. I was able to solve it. I was selecting wrongly the origin of the plane in the call of the function, it needed to be the centroid of the intersectionModel
