### ISSUE TITLE
surgicalGuideBases for mandible

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerBoneReconstructionPlanner#30]
@cmfsx, can you create a surgical plan with two surgicalGuideBases (one for each mandibleResectionPlane) using the segment editor?

**Comment by cmfsx** [comment]
@mauigna06 Sure will give it a go.

**Comment by mauigna06** [comment]
Thanks. I couldn't create one I liked

**Comment by mauigna06** [comment]
I found some pictures we can use as example:
![Captura](https://user-images.githubusercontent.com/19158307/109662768-2e543900-7b4a-11eb-8c07-dea515a81753.PNG)
![Captura04](https://user-images.githubusercontent.com/19158307/109662784-32805680-7b4a-11eb-8c26-7bfc684277ae.PNG)
![Captura09](https://user-images.githubusercontent.com/19158307/109662798-344a1a00-7b4a-11eb-9387-fb2c5124f25f.PNG)
![Captura16](https://user-images.githubusercontent.com/19158307/109662800-34e2b080-7b4a-11eb-9ab4-3a4fc89d3313.PNG)
![40902_2017_113_Fig2_HTML](https://user-images.githubusercontent.com/19158307/109664155-9eaf8a00-7b4b-11eb-8862-d89d7cd7dfeb.png)

And here there is also an example of a mandibleSurgicalGuide (and an iliacCrestSurgicalGuide):
https://www.xilloc.com/products-and-services/surgical-guides/
