### ISSUE TITLE
License of the module

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerBoneReconstructionPlanner#37]
Even though I'm doing my best creating this module. And the code from the branches is reviewed before going to main. This is not FDA approved medical software.
Should we add a sentence to the license like "For research use only. Not clinical use"?
I would like the user to know that he takes full responsability of the results while using the module for surgery planning. Should the license be more clear about this or it is enough with the current text?

**Comment by lassoan** [comment]
The license is very clearly states, in several sentences, that the software is provided "as is". When somebody installs Slicer for the first time there is a popup about this, too.

If you don't feel comfortable then you can add another popup that is displayed when the module is opened (and has a "do not show again" checkbox - one of the CTK dialog classes have this option).
