### ISSUE TITLE
vtkbool not working well for intersection operations

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerBoneReconstructionPlanner#41]
Hi @lassoan. Would you want me to talk with the developer of vtkbool?

I'm using fibulaBonePieces intersection to detect if a cut overlaps with the adjacent bone segment, cutting it. This is useful to detect when automatic fibula bone segments distancing works wrong or if the distance is too smal. The intersections of these fibulaBonePieces should have a non-empty result and that doesn't happen.

"Fibula Segment 0A-0B.vtk" intersection "Fibula Segment 1A-1B.vtk". The result is an empty model, it shouldn't be that way.
"Fibula Segment 1A-1B.vtk" intersection "Fibula Segment 2A-2B.vtk". The result is an empty model, it shouldn't be that way.

These are the files that give problems (I've checked and they do not have any non-manifold edges)
[Meshes.zip](https://github.com/lassoan/SlicerBoneReconstructionPlanner/files/6353906/Meshes.zip)

**Comment by lassoan** [comment]
Yes, please report this on the vtkbool issue tracker. Start it with thanking for the work on the vtkbool library and sending a link to our repository so that he can see what his work enables.

**Comment by cmfsx** [comment]
@mauigna06 rather than using the vtkbool to detect overlap is it better to use the model to model distance and  FindClosestPoint to detect the overlap ?  or is vtkbool the best way ?

**Comment by mauigna06** [comment]
I solved it using vtkCollisionDetectionFilter. The new feature of security margin is now working: an error appears if the distance between bone pieces is smaller than the security margin
