### ISSUE TITLE
Display the original transparent mandible

### ISSUE THREAD

**Issue by mrtig** [lassoan/SlicerBoneReconstructionPlanner#43]
Using the mandible-surgical-guide-feature branch. I like to display the original transparent mandible so I can better align the fibula fragments. Every time I press the update button the original model is hidden.
It would be nice if the model's visibility didn't change. Also it might be a good idea to add some user interface element so the user can quickly hide or make the original mandibula visible.

**Comment by mauigna06** [comment]
> Using the mandible-surgical-guide-feature branch. I like to display the original transparent mandible so I can better align the fibula fragments. Every time I press the update button the original model is hidden.
It would be nice if the model's visibility didn't change. Also it might be a good idea to add some user interface element so the user can quickly hide or make the original mandibula visible.

@cmfsx would you also like this?

**Comment by mauigna06** [comment]
Ok. So I'll add a button to show/hide the mandible model
