### ISSUE TITLE
Add Mandibular Scalar volume selector, Mandible Model/segment and Fibula model/segment

### ISSUE THREAD

**Issue by cmfsx** [lassoan/SlicerBoneReconstructionPlanner#5]
Would it be good if we add   to the top, 

- [x] Mandibular Scalar Volume selector 

- [x] Mandibular model/segment selector 

- [x] Fibula model/segmenet selector 

I can't think of a reason to add the fibula scalar volume now.

**Comment by lassoan** [comment]
To simplify things, we should probably require mandible and fibula segmentation (not models) as inputs. If for any reason someone has a model, it can be converted to segmentation in Segmentations module.

**Comment by mauigna06** [comment]
This is done

**Comment by mauigna06** [comment]
@cmfsx is there any reason to forbid users to use only 3D models to plan the surgery? E.g. they may choose the wrong resection margins in some cancer case because they can't validate the plan with the CT after finishing it
