### ISSUE TITLE
Meeting

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerBoneReconstructionPlanner#7]
Hi Andras and Manjula. Would you like to have our meeting next Tuesday at 4pm (Buenos Aires time)?

**Comment by lassoan** [comment]
OK, Dec 22, 2pm EST.

**Comment by cmfsx** [comment]
Yes I am fine with that!

**Comment by mauigna06** [comment]
We meet on Skype as last time

**Comment by cmfsx** [comment]
Sorry I cannot find the link can you please share it
